<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\AngleSharp.ReadOnlyDom.Streaming.AngleSharp\AngleSharp.ReadOnlyDom.Streaming.AngleSharp.csproj" />
  </ItemGroup>
</Project>
