<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" />
    <Using Include="AngleSharp.Html.Parser.Utf8" />
    <ProjectReference Include="..\AngleSharp.ReadOnlyDom\AngleSharp.ReadOnlyDom.csproj" />
    <ProjectReference Include="..\AngleSharp.ReadOnlyDom.Streaming\AngleSharp.ReadOnlyDom.Streaming.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AngleSharp.ReadOnlyDom.Benchmarks" />
  </ItemGroup>
</Project>
