<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AngleSharp.ReadOnlyDom.Benchmarks" />
    <InternalsVisibleTo Include="AngleSharp.ReadOnlyDom.Tests" />
  </ItemGroup>
</Project>
