<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Product>AngleSharp.ReadOnlyDom</Product>
        <PackageId>AngleSharp.ReadOnlyDom</PackageId>
        <Version>1.0.1</Version>
        <Authors>dv00d00</Authors>
        <Company>AngleSharp</Company>
        <Description>Lightweight DOM implementation with low memory allocations</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AngleSharp.ReadOnlyDom.Helpers"/>
    </ItemGroup>

</Project>
