// <auto-generated />
// Canonical source: AngleSharp 1.5.2+00e645d3f187dc451f37b319bf5361a4a26a71c1 HtmlElementFactory runtime metadata.

using AngleSharp.Common;
using AngleSharp.Dom;

namespace AngleSharp.ReadOnlyDom;

internal static class GeneratedTagMetadata
{
    public static NodeFlags GetFlags(StringOrMemory localName)
    {
        switch (localName.Length)
        {
            case 1:
                if (localName.Equals(TagNames.A))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.P))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.I))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.B))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.S))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.U))
                    return NodeFlags.HtmlFormatting;
                break;
            case 2:
                if (localName.Equals(TagNames.Li))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Td))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.Scoped;
                if (localName.Equals(TagNames.Dd))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Dt))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Hr))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Tr))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed;
                if (localName.Equals(TagNames.Ol))
                    return NodeFlags.Special | NodeFlags.HtmlListScoped;
                if (localName.Equals(TagNames.Ul))
                    return NodeFlags.Special | NodeFlags.HtmlListScoped;
                if (localName.Equals(TagNames.Br))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Dl))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Em))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.H1))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.H2))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.H3))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.H4))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.H5))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.H6))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Rb))
                    return NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Rp))
                    return NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Rt))
                    return NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Th))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.Scoped;
                if (localName.Equals(TagNames.Tt))
                    return NodeFlags.HtmlFormatting;
                break;
            case 3:
                if (localName.Equals(TagNames.Div))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Img))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Pre))
                    return NodeFlags.Special | NodeFlags.LineTolerance;
                if (localName.Equals(TagNames.Big))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.Col))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Dir))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Nav))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Rtc))
                    return NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd;
                if (localName.Equals(TagNames.Wbr))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Xmp))
                    return NodeFlags.Special | NodeFlags.LiteralText;
                break;
            case 4:
                if (localName.Equals(TagNames.Code))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.Area))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Base))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Body))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed;
                if (localName.Equals(TagNames.Font))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.Form))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Head))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Html))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.Scoped | NodeFlags.HtmlTableSectionScoped | NodeFlags.HtmlTableScoped;
                if (localName.Equals(TagNames.Link))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Main))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Menu))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Meta))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.NoBr))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.Time))
                    return NodeFlags.Special;
                break;
            case 5:
                if (localName.Equals(TagNames.Aside))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Embed))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Frame))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Input))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Param))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Small))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.Style))
                    return NodeFlags.Special | NodeFlags.LiteralText;
                if (localName.Equals(TagNames.Table))
                    return NodeFlags.Special | NodeFlags.Scoped | NodeFlags.HtmlTableSectionScoped | NodeFlags.HtmlTableScoped;
                if (localName.Equals(TagNames.Tbody))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.HtmlTableSectionScoped;
                if (localName.Equals(TagNames.Tfoot))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.HtmlTableSectionScoped;
                if (localName.Equals(TagNames.Thead))
                    return NodeFlags.Special | NodeFlags.ImplicitlyClosed | NodeFlags.HtmlTableSectionScoped;
                if (localName.Equals(TagNames.Title))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Track))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                break;
            case 6:
                if (localName.Equals(TagNames.Button))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Applet))
                    return NodeFlags.Special | NodeFlags.Scoped;
                if (localName.Equals(TagNames.Center))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Figure))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Footer))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Header))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Hgroup))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Iframe))
                    return NodeFlags.Special | NodeFlags.LiteralText;
                if (localName.Equals(TagNames.Keygen))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Object))
                    return NodeFlags.Special | NodeFlags.Scoped;
                if (localName.Equals(TagNames.Option))
                    return NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd | NodeFlags.HtmlSelectScoped;
                if (localName.Equals(TagNames.Output))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Script))
                    return NodeFlags.Special | NodeFlags.LiteralText;
                if (localName.Equals(TagNames.Select))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Source))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Strike))
                    return NodeFlags.HtmlFormatting;
                if (localName.Equals(TagNames.Strong))
                    return NodeFlags.HtmlFormatting;
                break;
            case 7:
                if (localName.Equals(TagNames.Address))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Article))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Bgsound))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Caption))
                    return NodeFlags.Special | NodeFlags.Scoped;
                if (localName.Equals(TagNames.Details))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.IsIndex))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Listing))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Marquee))
                    return NodeFlags.Special | NodeFlags.Scoped;
                if (localName.Equals(TagNames.NoEmbed))
                    return NodeFlags.Special | NodeFlags.LiteralText;
                if (localName.Equals(TagNames.Section))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Summary))
                    return NodeFlags.Special;
                break;
            case 8:
                if (localName.Equals(TagNames.BaseFont))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.Colgroup))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Fieldset))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Frameset))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.MenuItem))
                    return NodeFlags.SelfClosing | NodeFlags.Special;
                if (localName.Equals(TagNames.NoFrames))
                    return NodeFlags.Special | NodeFlags.LiteralText;
                if (localName.Equals(TagNames.NoScript))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Optgroup))
                    return NodeFlags.ImplicitlyClosed | NodeFlags.ImpliedEnd | NodeFlags.HtmlSelectScoped;
                if (localName.Equals(TagNames.Template))
                    return NodeFlags.Special | NodeFlags.Scoped | NodeFlags.HtmlTableSectionScoped | NodeFlags.HtmlTableScoped;
                if (localName.Equals(TagNames.Textarea))
                    return NodeFlags.Special | NodeFlags.LineTolerance;
                break;
            case 9:
                if (localName.Equals(TagNames.Plaintext))
                    return NodeFlags.Special;
                break;
            case 10:
                if (localName.Equals(TagNames.BlockQuote))
                    return NodeFlags.Special;
                if (localName.Equals(TagNames.Figcaption))
                    return NodeFlags.Special;
                break;
        }

        return NodeFlags.None;
    }
}
