<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <ProjectReference Include="..\..\AngleSharp.ReadOnlyDom\AngleSharp.ReadOnlyDom.csproj" />
    <ProjectReference Include="..\..\AngleSharp.ReadOnlyDom.Compact\AngleSharp.ReadOnlyDom.Compact.csproj" />
    <ProjectReference Include="..\..\AngleSharp.ReadOnlyDom.Streaming\AngleSharp.ReadOnlyDom.Streaming.csproj" />
  </ItemGroup>
</Project>
