<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net472</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference
      Include="BenchmarkDotNet.Diagnostics.Windows"
      Condition="'$(TargetFramework)' == 'net10.0' and $([MSBuild]::IsOSPlatform('Windows'))"
    />
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Polyfill" Condition="'$(TargetFramework)' == 'net472'" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\..\src\AngleSharp.ReadOnlyDom.Compact\AngleSharp.ReadOnlyDom.Compact.csproj"
      Condition="'$(TargetFramework)' == 'net10.0'"
    />
    <ProjectReference
      Include="..\..\src\AngleSharp.ReadOnlyDom.Streaming\AngleSharp.ReadOnlyDom.Streaming.csproj"
      Condition="'$(TargetFramework)' == 'net10.0'"
    />
    <ProjectReference Include="..\..\src\AngleSharp.ReadOnlyDom\AngleSharp.ReadOnlyDom.csproj" />
  </ItemGroup>
</Project>
