#!/usr/bin/env python3
"""Generate the WHATWG encoding-label lookup table."""

from __future__ import annotations

import json
import pathlib
import sys
import urllib.request


SOURCE = "https://encoding.spec.whatwg.org/encodings.json"
TARGET = (
    pathlib.Path(__file__).parents[1]
    / "src"
    / "AngleSharp.ReadOnlyDom.Streaming"
    / "Input"
    / "Generated"
    / "HtmlEncodingLabels.Generated.cs"
)


def csharp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True).replace("\\/", "/")


def main() -> None:
    source = sys.argv[1] if len(sys.argv) > 1 else SOURCE
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source) as response:
            groups = json.load(response)
    else:
        with open(source, encoding="utf-8") as stream:
            groups = json.load(stream)

    rows = sorted(
        (label, encoding["name"])
        for group in groups
        for encoding in group["encodings"]
        for label in encoding["labels"]
    )
    labels = "\n".join(f"        {csharp_string(label)}," for label, _ in rows)
    names = "\n".join(f"        {csharp_string(name)}," for _, name in rows)
    output = f'''// <auto-generated />
// Source: WHATWG Encoding Standard encodings.json ({SOURCE})

namespace AngleSharp.ReadOnlyDom.Streaming.Input;

internal static partial class HtmlEncodingLabels
{{
    private static readonly string[] Labels =
    [
{labels}
    ];

    private static readonly string[] Names =
    [
{names}
    ];

    private static bool TryGetName(ReadOnlySpan<char> label, out string name)
    {{
        var lower = 0;
        var upper = Labels.Length - 1;
        while (lower <= upper)
        {{
            var middle = lower + ((upper - lower) >> 1);
            var comparison = label.CompareTo(Labels[middle], StringComparison.OrdinalIgnoreCase);
            if (comparison == 0)
            {{
                name = Names[middle];
                return true;
            }}

            if (comparison < 0)
                upper = middle - 1;
            else
                lower = middle + 1;
        }}

        name = null!;
        return false;
    }}
}}
'''
    TARGET.write_text(output, encoding="utf-8")
    print(f"generated {len(rows)} encoding labels at {TARGET}")


if __name__ == "__main__":
    main()
