#!/usr/bin/env python3
"""Generate the allocation-free HTML named character reference table."""

from __future__ import annotations

import json
import pathlib
import sys
import urllib.request


SOURCE = "https://html.spec.whatwg.org/entities.json"
TARGET = pathlib.Path(__file__).parents[1] / "src" / "AngleSharp.ReadOnlyDom.Streaming" / "Utf8Tokenizer" / "Utf8HtmlEntityTable.Generated.cs"


def csharp_string(value: str) -> str:
    encoded = json.dumps(value, ensure_ascii=True)
    return encoded.replace("\\/", "/")


def main() -> None:
    source = sys.argv[1] if len(sys.argv) > 1 else SOURCE
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source) as response:
            entities = json.load(response)
    else:
        with open(source, encoding="utf-8") as stream:
            entities = json.load(stream)

    rows = sorted((name.removeprefix("&"), value["characters"]) for name, value in entities.items())
    names = "\n".join(f"        {csharp_string(name)}," for name, _ in rows)
    values = "\n".join(f"        {csharp_string(value)}," for _, value in rows)
    output = f'''// <auto-generated />
// Source: WHATWG HTML Living Standard entities.json ({SOURCE})

namespace AngleSharp.Streaming.Utf8;

internal static class Utf8HtmlEntityTable
{{
    private static readonly string[] Names =
    [
{names}
    ];

    private static readonly string[] Values =
    [
{values}
    ];

    internal static bool TryGet(ReadOnlySpan<byte> name, out string value)
    {{
        var lower = 0;
        var upper = Names.Length - 1;
        while (lower <= upper)
        {{
            var middle = lower + ((upper - lower) >> 1);
            var comparison = CompareAscii(name, Names[middle]);
            if (comparison == 0)
            {{
                value = Values[middle];
                return true;
            }}

            if (comparison < 0)
                upper = middle - 1;
            else
                lower = middle + 1;
        }}

        value = null!;
        return false;
    }}

    private static int CompareAscii(ReadOnlySpan<byte> left, string right)
    {{
        var common = Math.Min(left.Length, right.Length);
        for (var index = 0; index < common; index++)
        {{
            var difference = left[index] - right[index];
            if (difference != 0)
                return difference;
        }}

        return left.Length - right.Length;
    }}
}}
'''
    TARGET.write_text(output, encoding="utf-8")
    print(f"generated {len(rows)} entities at {TARGET}")


if __name__ == "__main__":
    main()
