using System.Reflection;
using System.Text;
using AngleSharp.Dom;
using AngleSharp.Html.Parser;

string[] hotTags =
[
    "a",
    "span",
    "code",
    "p",
    "li",
    "div",
    "td",
    "dd",
    "dt",
    "hr",
    "tr",
    "ol",
    "img",
    "i",
    "ul",
    "button",
    "b",
    "pre",
];
var hotTagRanks = hotTags.Select((tag, index) => (tag, index)).ToDictionary(item => item.tag, item => item.index);

var check = args.Length == 2 && args[0].Equals("--check", StringComparison.Ordinal);
if ((!check && args.Length != 1) || (check && args.Length != 2))
{
    Console.Error.WriteLine("Usage: AngleSharp.ReadOnlyDom.TagGenerator [--check] <generated-file>");
    return 2;
}

var angleSharp = typeof(TagNames).Assembly;
var factoryType =
    angleSharp.GetType("AngleSharp.Html.HtmlElementFactory", throwOnError: true)
    ?? throw new InvalidOperationException("AngleSharp HtmlElementFactory was not found.");
var factory =
    factoryType.GetField("Instance", BindingFlags.Static | BindingFlags.NonPublic)?.GetValue(null)
    ?? throw new InvalidOperationException("AngleSharp HtmlElementFactory.Instance was not found.");
var create =
    factoryType.GetMethod("Create", BindingFlags.Instance | BindingFlags.Public)
    ?? throw new InvalidOperationException("AngleSharp HtmlElementFactory.Create was not found.");

using var document = new HtmlParser().ParseDocument(string.Empty);
var tags = typeof(TagNames)
    .GetFields(BindingFlags.Public | BindingFlags.Static)
    .Where(field => field.FieldType == typeof(string))
    .Select(field => new Tag(field.Name, (string)field.GetValue(null)!))
    .GroupBy(tag => tag.Value, StringComparer.Ordinal)
    .Select(group => group.OrderBy(tag => tag.Constant, StringComparer.Ordinal).First())
    .Select(tag =>
    {
        var element = (IElement)create.Invoke(factory, [document, tag.Value, null, NodeFlags.None])!;
        var flags = element.Flags & ~(NodeFlags.HtmlMember | NodeFlags.SvgMember | NodeFlags.MathMember);
        return tag with { Flags = flags };
    })
    .Where(tag => tag.Flags != NodeFlags.None)
    .OrderBy(tag => tag.Value.Length)
    .ThenBy(tag => hotTagRanks.TryGetValue(tag.Value, out var rank) ? rank : int.MaxValue)
    .ThenBy(tag => tag.Value, StringComparer.Ordinal)
    .ToArray();

var version =
    angleSharp.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
    ?? angleSharp.GetName().Version?.ToString()
    ?? "unknown";
var output = new StringBuilder();
output.AppendLine("// <auto-generated />");
output.AppendLine($"// Canonical source: AngleSharp {version} HtmlElementFactory runtime metadata.");
output.AppendLine();
output.AppendLine("using AngleSharp.Common;");
output.AppendLine("using AngleSharp.Dom;");
output.AppendLine();
output.AppendLine("namespace AngleSharp.ReadOnlyDom;");
output.AppendLine();
output.AppendLine("internal static class GeneratedTagMetadata");
output.AppendLine("{");
output.AppendLine("    public static NodeFlags GetFlags(StringOrMemory localName)");
output.AppendLine("    {");
output.AppendLine("        switch (localName.Length)");
output.AppendLine("        {");

foreach (var lengthGroup in tags.GroupBy(tag => tag.Value.Length))
{
    output.AppendLine($"            case {lengthGroup.Key}:");
    foreach (var tag in lengthGroup)
    {
        output.AppendLine($"                if (localName.Equals(TagNames.{tag.Constant}))");
        output.AppendLine($"                    return {FormatFlags(tag.Flags)};");
    }

    output.AppendLine("                break;");
}

output.AppendLine("        }");
output.AppendLine();
output.AppendLine("        return NodeFlags.None;");
output.AppendLine("    }");
output.AppendLine("}");

var outputPath = Path.GetFullPath(args[^1]);
var generated = output.ToString().ReplaceLineEndings("\n");
if (check)
{
    var current = File.ReadAllText(outputPath).ReplaceLineEndings("\n");
    if (!current.Equals(generated, StringComparison.Ordinal))
    {
        Console.Error.WriteLine($"Generated tag metadata is stale: {outputPath}");
        return 1;
    }

    Console.WriteLine($"Verified {tags.Length} generated tag metadata entries against AngleSharp {version}");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
Console.WriteLine($"Generated {tags.Length} tag metadata entries from AngleSharp {version} at {outputPath}");
return 0;

static string FormatFlags(NodeFlags flags)
{
    var remaining = Convert.ToUInt64(flags);
    var names = Enum.GetValues<NodeFlags>()
        .Select(flag => (Flag: flag, Value: Convert.ToUInt64(flag)))
        .Where(item => item.Value != 0 && (item.Value & (item.Value - 1)) == 0 && (remaining & item.Value) != 0)
        .OrderBy(item => item.Value)
        .Select(item => $"NodeFlags.{item.Flag}")
        .ToArray();
    foreach (var flag in Enum.GetValues<NodeFlags>())
    {
        var value = Convert.ToUInt64(flag);
        if (value != 0 && (value & (value - 1)) == 0)
            remaining &= ~value;
    }

    if (remaining != 0)
        throw new InvalidOperationException($"Unrecognized NodeFlags bits: 0x{remaining:X}");
    return string.Join(" | ", names);
}

internal sealed record Tag(string Constant, string Value, NodeFlags Flags = NodeFlags.None);
