<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net481</TargetFrameworks>
    <SignAssembly>false</SignAssembly>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>false</WarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="CsQuery" Condition=" '$(TargetFramework)' == 'net481' " />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="System.Buffers" />
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="Polyfill" Condition=" '$(TargetFramework)' == 'net481' " PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="HttpParsingBenchmark.cs" Condition=" '$(TargetFramework)' == 'net481' " />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AngleSharp.ReadOnlyDom\AngleSharp.ReadOnlyDom.csproj" />
    <ProjectReference
      Include="..\AngleSharp.ReadOnlyDom.Helpers\AngleSharp.ReadOnlyDom.Helpers.csproj"
      Condition=" '$(TargetFramework)' != 'net481' "
    />
  </ItemGroup>
</Project>
